---
#Подготовка всех нод для развертывания кластера кубера

- name: Подготовка нод к работе с K8s
  hosts: all
  become: true
  roles:
    - k8s_prereqs
# Просто описываем группы хостов( она одна) и указываем роль,которую описали.
