---
- name: Подготовка всех нод
  hosts: k8s
  become: true
  roles:
    - common

- name: Инициализация мастера
  hosts: master
  become: true
  roles:
    - master

- name: Подключение воркеров
  hosts: worker
  become: true
  roles:
    - worker
